### ISSUE TITLE
How to Improve the labels that don't fit in the allocated grid?

### ISSUE THREAD

**Issue by kulemantu** [hunterachieng/shara-assessment#4]
E.g. Mobile Number, Business category

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/907164/215256916-4e4ca508-28e8-417e-ae50-2ac1369198a1.png">

**Comment by kulemantu** [comment]
Or we can recommend shorter labels like "Phone" and "Category". 
What do you think @hunterachieng?

**Comment by hunterachieng** [comment]
I removed the long ones and added short ones
