### ISSUE TITLE
How do I get to the home page from the Users page?

### ISSUE THREAD

**Issue by kulemantu** [hunterachieng/shara-assessment#5]
I was having trouble clicking back to the main page from the Users page.
Where should I click for that? I was expecting that "Hunter" would be the link to do that.

<img width="1270" alt="image" src="https://user-images.githubusercontent.com/907164/215257001-c0a05057-0ca5-4d00-9af0-a0cc79959f0f.png">

**Comment by hunterachieng** [comment]
Fixed
