### ISSUE TITLE
Document in README reasons for choosing Ant Design over other component frameworks

### ISSUE THREAD

**Issue by kulemantu** [hunterachieng/shara-assessment#6]
@hunterachieng I'm interested in the thought process to choose Ant Design. I actually really like it - I think you should add a very short sentence in README on why you chose Ant Design over others like Material, Chakra, etc. e.g "I assessed A, B, C. Chose A because it makes it easy to scaffold, and..."

(Sell the next developer on your decision) 😄

**Comment by hunterachieng** [comment]
Resolved
